#!/usr/bin/env bash
# This script displays usernames, user IDs, and home directories from passwd

while IFS=: read -r username password userid groupid info home shell
do
    echo "$username:$userid:$home"
done < /etc/passwd
