#!/usr/bin/env bash
# This script displays usernames, user IDs, and home directories from passwd

while IFS=: read -r username _ userid _ _ home _
do
    echo "$username:$userid:$home"
done < /etc/passwd
